INSERT INTO `tipi_edificio`(`Nome`, `Descrizione`) VALUES ("Torre dell'arciere", "Le torri degli arcieri hanno una gittata maggiore dei cannoni e possono attaccare anche i nemici volanti.");
INSERT INTO `tipi_edificio`(`Nome`, `Descrizione`) VALUES("Cannone", "I cannoni sono ottimi per difendere i punti strategici. Migliorali per aumentarne la potenza di fuoco, ma ricorda che le difese non possono sparare mentre vengono migliorate.");
INSERT INTO `tipi_edificio`(`Nome`, `Descrizione`) VALUES("Arco-X", "L'arco-X scocca dardi mistici dal potere terrificante. Caricalo con elisir per attivarlo automaticamente. Puoi impostarlo in modo che colpisca unità di terra a lunga distanza o tutti gli obiettivi a corto raggio.");
INSERT INTO `tipi_edificio`(`Nome`, `Descrizione`) VALUES("Torre infernale", "Accendi la fiamma a elisir nero della torre infernale per infliggere danni incredibili a bersagli singoli o per arrostire molteplici obiettivi contemporaneamente.");
INSERT INTO `tipi_edificio`(`Nome`, `Descrizione`) VALUES("Torre dello stregone", "La difesa arcana definitiva! Le torri dello stregone lanciano potenti incantesimi ad area che colpiscono sia le truppe volanti che quelle di terra.");
INSERT INTO `tipi_edificio`(`Nome`, `Descrizione`) VALUES("Difesa aerea", "Questa torre antiaerea è letale contro i nemici volanti, ma non può colpire i nemici a terra. Posizionala con attenzione in modo da coprire uno spazio aereo il più ampio possibile.");
INSERT INTO `tipi_edificio`(`Nome`, `Descrizione`) VALUES("Miniera d'oro", "La miniera d'oro produce oro. Migliorala per aumentare la produzione e la quantità di oro conservato.");
INSERT INTO `tipi_edificio`(`Nome`, `Descrizione`) VALUES("Estrattore di elisir", "L'elisir è estratto dalle falde sotterranee presenti sotto il tuo villaggio. Migliora i tuoi estrattori di elisir per massimizzarne la produzione.");
INSERT INTO `tipi_edificio`(`Nome`, `Descrizione`) VALUES("Trivella per elisir nero", "I nostri costruttori hanno finalmente trovato un modo per estrarre elisir nero allo stato puro, la forma più rara di questa sostanza magica.");
INSERT INTO `tipi_edificio`(`Nome`, `Descrizione`) VALUES("Municipio", "Questo è il cuore del tuo villaggio. Aumentando il livello del municipio sbloccherai nuovi edifici, difese, trappole e molto altro ancora. Distruggendo il municipio di un avversario vincerai la battaglia e guadagnerai una stella. Distruggendo il 50% degli edifici nemici otterrai una seconda stella, mentre la distruzione del 100% ti farà guadagnare tre stelle. Attenzione: anche i nemici proveranno a distruggere il tuo municipio!");
INSERT INTO `tipi_edificio`(`Nome`, `Descrizione`) VALUES("Laboratorio", "Quali oscuri segreti nascondono gli stregoni all'interno del loro laboratorio? Nessuno ha avuto il coraggio di scoprirlo. Tutto quello che sappiamo è che la loro ricerca rende incantesimi e truppe migliori più potenti, più veloci e più resistenti!");
INSERT INTO `tipi_edificio`(`Nome`, `Descrizione`) VALUES("Castello del clan", "Il castello del clan ora ospita la tesoreria e tutte le truppe e gli incantesimi donati dai membri del tuo clan.");
INSERT INTO `tipi_edificio`(`Nome`, `Descrizione`) VALUES("Accampamento", "Le tue truppe stazionano negli accampamenti. Costruiscine altri e migliorali per assemblare un esercito potente.");

INSERT INTO `tipi_truppe`(`Nome`, `Descrizione`) VALUES ("Barbaro", "Questo impavido guerriero getta nel caos i villaggi nemici con l'aiuto dei suoi possenti muscoli e dei suoi notevoli baffi. Scatena un'orda di barbari e goditi il finimondo!");
INSERT INTO `tipi_truppe`(`Nome`, `Descrizione`) VALUES("Arciere", "Questi tiratori scelti preferiscono mantenere le distanze, sia sul campo di battaglia che nella vita. Niente li rende più felici che dedicarsi con risolutezza all'abbattimento del proprio bersaglio.");
INSERT INTO `tipi_truppe`(`Nome`, `Descrizione`) VALUES("Gigante", "Questi ragazzoni sembrano tranquilli, ma non appena vedono una torre dell'arciere o un cannone, scatenano tutta la loro furia! Lenti ma resistenti, sono meglio utilizzati per assorbire i colpi.");
INSERT INTO `tipi_truppe`(`Nome`, `Descrizione`) VALUES("Goblin", "Queste creaturine fastidiose sono interessate a una cosa sola: il BOTTINO! Sono più veloci di una trappola a scatto e la loro fame di risorse è sconfinata.");
INSERT INTO `tipi_truppe`(`Nome`, `Descrizione`) VALUES("Spaccamuro", "Niente riscalda il cuore glaciale di uno spaccamuro come l'esplosione di un muro. Un plotone di questi non morti provocherà un bel botto che aprirà la strada alle tue unità di terra.");
INSERT INTO `tipi_truppe`(`Nome`, `Descrizione`) VALUES("Mongolfiera", "Questi scheletri di grado superiore hanno barattato il piacere nel distruggere mura col piacere nel distruggere le difese. Schierali per annientare fastidiosi mortai e cannoni!");
INSERT INTO `tipi_truppe`(`Nome`, `Descrizione`) VALUES("Guaritore", "Questa maestosa creatura vive per proteggere e aiutare le truppe a lei amiche. Qualsiasi esercito può trarre beneficio dal suo aiuto curativo, purché tu riesca a proteggerla dalle difese aeree!");
INSERT INTO `tipi_truppe`(`Nome`, `Descrizione`) VALUES("Drago", "Il potere dei draghi è noto in tutto il paese. Questo squamoso terrore dei cieli non prova pietà e nulla può sfuggire al suo alito fiammeggiante.");
INSERT INTO `tipi_truppe`(`Nome`, `Descrizione`) VALUES("Stregone", "Lo stregone è una presenza inquietante sul campo di battaglia. Schieralo con qualche suo collega e sferra attacchi distruttivi concentrati su qualsiasi cosa, a terra o in aria!");
INSERT INTO `tipi_truppe`(`Nome`, `Descrizione`) VALUES("Pekka", "P.E.K.K.A è un cavaliere? Un samurai? Un robot? Nessuno lo sa! La sua armatura assorbe anche i colpi più potenti.");

INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (100, "Torre dell'arciere", 1);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (150, "Torre dell'arciere", 2);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (200, "Torre dell'arciere", 3);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (350, "Torre dell'arciere", 4);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (780, "Torre dell'arciere", 5);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (1000, "Torre dell'arciere", 6);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (180, "Cannone", 1);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (290, "Cannone", 2);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (360, "Cannone", 3);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (450, "Cannone", 4);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (876, "Cannone", 5);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (1204, "Cannone", 6);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (500, "Arco-X", 1);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (640, "Arco-X", 2);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (735, "Arco-X", 3);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (818, "Arco-X", 4);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (1100, "Arco-X", 5);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (1300, "Arco-X", 6);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (610, "Torre infernale", 1);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (820, "Torre infernale", 2);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (950, "Torre infernale", 3);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (1120, "Torre infernale", 4);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (1430, "Torre infernale", 5);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (1600, "Torre infernale", 6);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (300, "Torre dello stregone", 1);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (400, "Torre dello stregone", 2);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (500, "Torre dello stregone", 3);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (600, "Torre dello stregone", 4);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (800, "Torre dello stregone", 5);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (900, "Torre dello stregone", 6);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (200, "Difesa aerea", 1);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (400, "Difesa aerea", 2);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (600, "Difesa aerea", 3);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (800, "Difesa aerea", 4);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (1000, "Difesa aerea", 5);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (1200, "Difesa aerea", 6);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (100, "Miniera d'oro", 1);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (200, "Miniera d'oro", 2);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (300, "Miniera d'oro", 3);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (320, "Miniera d'oro", 4);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (340, "Miniera d'oro", 5);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (360, "Miniera d'oro", 6);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (100, "Estrattore di elisir", 1);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (200, "Estrattore di elisir", 2);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (300, "Estrattore di elisir", 3);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (320, "Estrattore di elisir", 4);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (340, "Estrattore di elisir", 5);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (360, "Estrattore di elisir", 6);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (100, "Trivella per elisir nero", 1);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (200, "Trivella per elisir nero", 2);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (300, "Trivella per elisir nero", 3);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (320, "Trivella per elisir nero", 4);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (340, "Trivella per elisir nero", 5);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (360, "Trivella per elisir nero", 6);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (1000, "Municipio", 1);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (2000, "Municipio", 2);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (3000, "Municipio", 3);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (4000, "Municipio", 4);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (5000, "Municipio", 5);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (5999, "Municipio", 6);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (1000, "Laboratorio", 1);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (2000, "Laboratorio", 2);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (3000, "Laboratorio", 3);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (4000, "Laboratorio", 4);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (5000, "Laboratorio", 5);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (5999, "Laboratorio", 6);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (1000, "Accampamento", 1);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (2000, "Accampamento", 2);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (3000, "Accampamento", 3);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (4000, "Accampamento", 4);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (5000, "Accampamento", 5);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (5999, "Accampamento", 6);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (1000, "Castello del clan", 1);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (2000, "Castello del clan", 2);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (3000, "Castello del clan", 3);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (4000, "Castello del clan", 4);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (5000, "Castello del clan", 5);
INSERT INTO `statistiche_edifici_migliorati`(`PuntiVita`, `Nome`, `LivelloMiglioramento`) VALUES (5999, "Castello del clan", 6);

INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (1, 5000,30,500,60,25,"Barbaro");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (2, 10000,60,800,80,32,"Barbaro");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (3, 15000,90,950,74,39,"Barbaro");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (4, 20000,120,1100,80,48,"Barbaro");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (5, 25000,150,1450,92,55,"Barbaro");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (6, 30000,180,1810,108,63,"Barbaro");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (1, 5000,30,500,60,25,"Arciere");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (2, 10000,60,800,80,32,"Arciere");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (3, 15000,90,950,74,39,"Arciere");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (4, 20000,120,1100,80,48,"Arciere");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (5, 25000,150,1450,92,55,"Arciere");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (6, 30000,180,1810,108,63,"Arciere");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (1, 5000,30,500,60,25,"Gigante");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (2, 10000,60,800,80,32,"Gigante");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (3, 15000,90,950,74,39,"Gigante");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (4, 20000,120,1100,80,48,"Gigante");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (5, 25000,150,1450,92,55,"Gigante");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (6, 30000,180,1810,108,63,"Gigante");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (1, 5000,30,500,60,25,"Goblin");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (2, 10000,60,800,80,32,"Goblin");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (3, 15000,90,950,74,39,"Goblin");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (4, 20000,120,1100,80,48,"Goblin");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (5, 25000,150,1450,92,55,"Goblin");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (6, 30000,180,1810,108,63,"Goblin");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (1, 5000,30,500,60,25,"Spaccamuro");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (2, 10000,60,800,80,32,"Spaccamuro");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (3, 15000,90,950,74,39,"Spaccamuro");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (4, 20000,120,1100,80,48,"Spaccamuro");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (5, 25000,150,1450,92,55,"Spaccamuro");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (6, 30000,180,1810,108,63,"Spaccamuro");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (1, 5000,30,500,60,25,"Mongolfiera");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (2, 10000,60,800,80,32,"Mongolfiera");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (3, 15000,90,950,74,39,"Mongolfiera");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (4, 20000,120,1100,80,48,"Mongolfiera");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (5, 25000,150,1450,92,55,"Mongolfiera");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (6, 30000,180,1810,108,63,"Mongolfiera");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (1, 5000,30,500,60,25,"Guaritore");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (2, 10000,60,800,80,32,"Guaritore");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (3, 15000,90,950,74,39,"Guaritore");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (4, 20000,120,1100,80,48,"Guaritore");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (5, 25000,150,1450,92,55,"Guaritore");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (6, 30000,180,1810,108,63,"Guaritore");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (1, 5000,30,500,60,25,"Drago");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (2, 10000,60,800,80,32,"Drago");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (3, 15000,90,950,74,39,"Drago");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (4, 20000,120,1100,80,48,"Drago");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (5, 25000,150,1450,92,55,"Drago");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (6, 30000,180,1810,108,63,"Drago");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (1, 5000,30,500,60,25,"Stregone");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (2, 10000,60,800,80,32,"Stregone");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (3, 15000,90,950,74,39,"Stregone");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (4, 20000,120,1100,80,48,"Stregone");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (5, 25000,150,1450,92,55,"Stregone");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (6, 30000,180,1810,108,63,"Stregone");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (1, 5000,30,500,60,25,"Pekka");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (2, 10000,60,800,80,32,"Pekka");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (3, 15000,90,950,74,39,"Pekka");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (4, 20000,120,1100,80,48,"Pekka");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (5, 25000,150,1450,92,55,"Pekka");
INSERT INTO `statistiche_truppe_migliorate`(`LivelloMiglioramento`, `DurataMS`, `Costo`, `PuntiEsperienzaConferiti`, `PuntiVita`, `DanniInflitti`, `Nome`) VALUES (6, 30000,180,1810,108,63,"Pekka");